### ISSUE TITLE
Unable to find devce

### ISSUE THREAD

**Issue by 0xPBIT** [LoneWanderer-GH/RaspiVWS#5] opened 2020-06-29 03:31 UTC
**Describe the bug**
I have tried multiple cameras, and a specifically a Logitech C920. The program is unable to detect the cameras:
`Error [1]: Device /dev/video0 required but could not be found. Aborting.`

**To Reproduce**
1. Connect camera to device
2. Ensure the camera is recognized by the pi: `v4l2-ctl --list-devices`
3. Check output: `HD Pro Webcam C920 (usb-0000:01:00.0-1.3): /dev/video0 /dev/video1`
4. Run script ` ./Raspi_VLC_Webcam_Stream.sh 0`

**Expected behavior**
The program should run.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/5788534/85970083-f67b6d00-b98e-11ea-9f7a-0a175c9f6ef9.PNG)

**Comment by m-kozlowski** [comment] 2020-07-13 21:47
change 
`if [ -f "${WEBCAM_DEVICE}" ] ; then`
to
`if [ -e "${WEBCAM_DEVICE}" ] ; then`

**Comment by LoneWanderer-GH** [comment] 2020-07-28 00:11
Closing as duplicate of #2.
I hope to push the (known) fix this week.

**Closed as completed by LoneWanderer-GH** 2020-07-28 00:11 UTC
Labels: duplicate
